name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_version: ["20.10.5", "19.03.15"]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t dind --build-arg DOCKERIMAGE_TAG=${{ matrix.docker_version }}-dind .
      - name: Run the built image
        run: docker run --name test-container -d --privileged dind
      - name: Verify Docker is accessible in the built image. (Retry 3 times)
        run: for i in {1..3}; do docker exec --tty test-container env TERM=xterm docker info && break || sleep 10; done

  release:
    name: Release docker image
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        docker_version: ["20.10.5", "19.03.15"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mreimbold/debian10-dind:latest
          build-args: |
            DOCKERIMAGE_TAG=20.10.5-dind

      - name: Build and push specific tags
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mreimbold/debian10-dind:${{ matrix.docker_version }}
          build-args: |
            DOCKERIMAGE_TAG=${{ matrix.docker_version }}-dind
